### ISSUE TITLE
Presentation from Tango Meeting

### ISSUE THREAD

**Issue by LJBD** [nleclercq/jupyter-for-controls#1]
Hello, Nicholas!

Many thanks for uploading this project!
I have a request: could you please also upload (here or in a separate repository) your presentation from the Tango Meeting?

Best regards,
Łukasz

**Comment by nleclercq** [comment]
Will do that ASAP.
Thanks.

**Comment by nleclercq** [comment]
[Done!](https://github.com/nleclercq/jupyter-for-controls/tree/master/tango_meeting_florence_0617)
